 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using IConnection;using ICollection;
namespace DataStoring
{

	interface ICollection
	{

		public IDataStore DataStore { get; }

		Task<bool> Insert(string entity);
		Task<bool> Update(string entity);
		Task<bool> Delete(string entity);
	}

}
