 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace DataStoring
{
	interface IConnection
	{
		public string ProviderName { get; }

		Task<bool> IsDataStoreExists( string storeName );
		Task<IDataStore> GetDataStoreByName( string storeName );
		Task<IDataStore> CreateDataStore( string storeName );
		Task<IDataStore> DropDataStore( IDataStore dataStore );
	}
}
