 
// <auto-generated>
//     This code was generated by unicontract
//     see more information: https://github.com/gyorgy-gulyas/UniContract
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace DataStoring
{
	interface IDataStore
	{
		public IConnection Connection { get; }

		Task<bool> IsCollectionExists( string collectionName );
		Task<ICollection<T>> GetCollectionByName<T>( string collectionName ) where T: IEntity;
		Task<ICollection<T>> CreateCollection<T>( string collectionName ) where T: IEntity;
		Task<ICollection<T>> DropCollection<T>( ICollection collection ) where T: IEntity;
	}
}
